name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      run: sudo apt -y install gcc-arm-none-eabi
    - name: check toolchain
      run: arm-none-eabi-gcc --version
    - name: build
      run: cd varmint_10X && mkdir build && cd build && cmake .. && make
