---
name: "pre-release"
on:
  push:
    branches:
      - "main"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install toolchain
      run: sudo apt -y install gcc-arm-none-eabi ninja-build
    - name: check toolchain
      run: |
        arm-none-eabi-gcc --version
        ninja --version
    - name: build varmint_10X
      run: |
        cmake --preset varmint-10X-debug
        cmake --build build/varmint-10X-debug    
    - name: build varmint_11X
      run: |
        cmake --preset varmint-11X-debug
        cmake --build build/varmint-11X-debug      
    - name: build pixracer pro
      run: |
        cmake --preset pixracer-pro-debug
        cmake --build build/pixracer-pro-debug 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          build/varmint-10X-debug/output/varmint_10X.hex
          build/varmint-10X-debug/output/varmint_11X.hex
          build/pixracer-pro-debug/output/pixracer_pro.hex
