---
name: "Release"
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: install toolchain
        run: sudo apt -y install gcc-arm-none-eabi ninja-build
      - name: check toolchain
        run: |
          arm-none-eabi-gcc --version
          ninja --version
      - name: build varmint_10X
        run: |
          cmake --preset varmint-10X-release
          cmake --build build/varmint-10X-release    
      - name: build varmint_11X
        run: |
          cmake --preset varmint-11X-release
          cmake --build build/varmint-11X-release      
      - name: build pixracer pro
        run: |
          cmake --preset pixracer-pro-release
          cmake --build build/pixracer-pro-release 
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/varmint-10X-release/output/varmint_10X.hex
            build/varmint-10X-release/output/varmint_11X.hex
            build/pixracer-pro-release/output/pixracer_pro.hex
