name: Varmint Boards Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install toolchain
      run: sudo apt -y install gcc-arm-none-eabi ninja-build
    - name: check toolchain
      run: |
        arm-none-eabi-gcc --version
        ninja --version
    - name: build varmint_10X
      run: |
        cmake --preset varmint-10X-release
        cmake --build build/varmint-10X-release 
    - name: build varmint_11X
      run: |
        cmake --preset varmint-11X-release
        cmake --build build/varmint-11X-release 
    - name: build pixracer pro
      run: |
        cmake --preset pixracer-pro-release
        cmake --build build/pixracer-pro-release 