name: Varmint Boards Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install toolchain
      run: sudo apt -y install gcc-arm-none-eabi
    - name: check toolchain
      run: arm-none-eabi-gcc --version
    - name: build varmint_10X
      run: mkdir varmint_10X_build && cd varmint_10X_build && cmake .. -DBOARD_TO_BUILD=varmint_10X && make    
    - name: build varmint_11X
      run: mkdir varmint_11X_build && cd varmint_11X_build && cmake .. -DBOARD_TO_BUILD=varmint_11X && make
    - name: build pixracer pro
      run: mkdir pixracer_pro_build && cd pixracer_pro_build && cmake .. -DBOARD_TO_BUILD=pixracer_pro && make
